import cohere
import os
import asyncio
from concurrent.futures import ThreadPoolExecutor
from services.tracked_ai_clients import TrackedCohereClient


class AIDAO:
    def __init__(self):
        # Use TrackedCohereClient for automatic logging and fallback
        try:
            self.co = TrackedCohereClient()
        except Exception:
            self.co = None
        self.executor = ThreadPoolExecutor(max_workers=3)

    async def generate_text(self, prompt: str, system_message="") -> str:
        ''' prompt: message that the AI uses to generate a response. This can also be generated by the user.

        system_message: context/strict guidelines for the AI to follow, use if you're allowing the user to freely type a prompt.'''
        try:
            # Run the synchronous Cohere call in a thread pool to avoid blocking
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                self.executor,
                self._call_cohere,
                prompt,
                system_message
            )
            return response
        except Exception as e:
            raise Exception(f"Error generating AI text: {str(e)}")

    def _call_cohere(self, prompt: str, system_message: str) -> str:
        """Synchronous Cohere API call wrapper"""
        try:
            if self.co is None:
                raise Exception("Cohere client not configured")
            response = self.co.chat(
                model="command-a-03-2025",
                messages=[
                    {"role": "system", "content": system_message},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.message.content[0].text
        except Exception as e:
            raise Exception(f"Error calling Cohere API: {str(e)}")



# instance to call
ai_dao = AIDAO()
